---
title: "Wrangling"
author: "Carter Martindale"
date: "10/14/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(dplyr)
library(ggplot2)
library(readr)
library(lubridate)
library(janitor)
library(rstanarm)
library(readxl)
```

## SC case centered

```{r case}

d<- read_csv("raw_data/SCDB_2020_01_caseCentered_LegalProvision.csv", col_names = TRUE, cols(
  caseId = col_character(),
  docketId = col_character(),
  caseIssuesId = col_character(),
  voteId = col_character(),
  dateDecision = col_character(),
  decisionType = col_double(),
  usCite = col_character(),
  sctCite = col_character(),
  ledCite = col_character(),
  lexisCite = col_character(),
  term = col_double(),
  naturalCourt = col_double(),
  chief = col_character(),
  docket = col_character(),
  caseName = col_character(),
  dateArgument = col_character(),
  dateRearg = col_character(),
  petitioner = col_double(),
  petitionerState = col_double(),
  respondent = col_double(),
  respondentState = col_double(),
  jurisdiction = col_double(),
  adminAction = col_double(),
  adminActionState = col_double(),
  threeJudgeFdc = col_double(),
  caseOrigin = col_double(),
  caseOriginState = col_double(),
  caseSource = col_double(),
  caseSourceState = col_double(),
  lcDisagreement = col_double(),
  certReason = col_double(),
  lcDisposition = col_double(),
  lcDispositionDirection = col_double(),
  declarationUncon = col_double(),
  caseDisposition = col_double(),
  caseDispositionUnusual = col_double(),
  partyWinning = col_double(),
  precedentAlteration = col_double(),
  voteUnclear = col_double(),
  issue = col_double(),
  issueArea = col_double(),
  decisionDirection = col_double(),
  decisionDirectionDissent = col_double(),
  authorityDecision1 = col_double(),
  authorityDecision2 = col_double(),
  lawType = col_double(),
  lawSupp = col_double(),
  lawMinor = col_character(),
  majOpinWriter = col_double(),
  majOpinAssigner = col_double(),
  splitVote = col_double(),
  majVotes = col_double(),
  minVotes = col_double()
)) %>% 
  clean_names()

d_reformat <- d %>% 
  mutate(date_decision_new = mdy(date_decision),
         date_argument_new = mdy(date_argument),
         date_rearg_new = mdy(date_rearg))

# Here I created a new date column that would be workable as
# a date rather than simply a character, and I cleaned up
# the names. 

```

```{r plot}

d_reformat %>% 
  group_by(issue_area) %>% 
  filter(issue_area %in% c(2, 3, 5)) %>% 
  ggplot(aes(x = issue_area, fill = chief)) +
  geom_bar(position = "dodge") +
  facet_wrap(~decision_direction)

d_reformat %>% 
  ggplot(aes(x = issue_area, fill = chief)) +
  geom_bar(position = "dodge")

 plot3 <- d_reformat %>% 
  filter(decision_direction %in% c(1, 2)) %>% 
  ggplot(aes(x = term, fill = chief)) +
  geom_bar(position = "dodge") +
  facet_wrap(~decision_direction,
             labeller = labeller(decision_direction = c(
               "1" = "Conservative", "2" = "Liberal"))) +
  scale_fill_discrete(name = "Chief",
                      breaks = c("Vinson", "Warren",
                                 "Burger", "Rehnquist",
                                 "Roberts")) +
  labs(title = "Direction of SCOTUS Rulings",
       x = "Term",
       y = "Number of Rulings")

```

```{r justice}

justice <- read_csv("raw_data/SCDB_2020_01_justiceCentered_Citation.csv", col_names = TRUE, cols(
  caseId = col_character(),
  docketId = col_character(),
  caseIssuesId = col_character(),
  voteId = col_character(),
  dateDecision = col_character(),
  decisionType = col_double(),
  usCite = col_character(),
  sctCite = col_character(),
  ledCite = col_character(),
  lexisCite = col_character(),
  term = col_double(),
  naturalCourt = col_double(),
  chief = col_character(),
  docket = col_character(),
  caseName = col_character(),
  dateArgument = col_character(),
  dateRearg = col_character(),
  petitioner = col_double(),
  petitionerState = col_double(),
  respondent = col_double(),
  respondentState = col_double(),
  jurisdiction = col_double(),
  adminAction = col_double(),
  adminActionState = col_double(),
  threeJudgeFdc = col_double(),
  caseOrigin = col_double(),
  caseOriginState = col_double(),
  caseSource = col_double(),
  caseSourceState = col_double(),
  lcDisagreement = col_double(),
  certReason = col_double(),
  lcDisposition = col_double(),
  lcDispositionDirection = col_double(),
  declarationUncon = col_double(),
  caseDisposition = col_double(),
  caseDispositionUnusual = col_double(),
  partyWinning = col_double(),
  precedentAlteration = col_double(),
  voteUnclear = col_double(),
  issue = col_double(),
  issueArea = col_double(),
  decisionDirection = col_double(),
  decisionDirectionDissent = col_double(),
  authorityDecision1 = col_double(),
  authorityDecision2 = col_double(),
  lawType = col_double(),
  lawSupp = col_double(),
  lawMinor = col_character(),
  majOpinWriter = col_double(),
  majOpinAssigner = col_double(),
  splitVote = col_double(),
  majVotes = col_double(),
  minVotes = col_double(),
  justice = col_double(),
  justiceName = col_character(),
  vote = col_double(),
  opinion = col_double(),
  direction = col_double(),
  majority = col_double(),
  firstAgreement = col_double(),
  secondAgreement = col_double())) %>% 
  select(voteId, dateDecision, term, chief,
         caseOriginState, issue, issueArea,
         decisionDirection, justice, justiceName, vote,
         decisionDirectionDissent, majOpinWriter, direction) %>% 
  clean_names() %>% 
  drop_na(direction)

justice$direction[which(justice$direction == 2)] <- 0

summary(justice)


case_reformat %>% 
        filter(issue_area == 3) %>% 
        ggplot(aes(x = issue_area, fill = chief)) +
            geom_bar(position = "dodge")

fit <- justice %>% 
            filter(justice_name %in% c("JGRoberts", "CThomas",
                                       "SGBreyer", "SAAlito",
                                       "SSotomayor"),
                   issue_area == 3)

stan_glm(direction ~ justice_name - 1,
         data = fit,
         refresh =)
```

1 cert
2 appeal
3 bail
4 certification
5 docketing fee
6 rehearing or restored to calendar for reargument
7 injunction
8 mandamus
9 original
10 prohibition
12 stay
13 writ of error
14 writ of habeas corpus
15 unspecified, other
```{r}
d$jurisdiction[which(d$jurisdiction == 1)] <- "cert"
d$jurisdiction[which(d$jurisdiction == 2)] <- "appeal"
d$jurisdiction[which(d$jurisdiction == 3)] <- "bail"
d$jurisdiction[which(d$jurisdiction == 4)] <- "certification"
d$jurisdiction[which(d$jurisdiction == 5)] <- "docketing fee"
d$jurisdiction[which(d$jurisdiction == 6)] <- "rehearsing or restored to calendar for reargument"
d$jurisdiction[which(d$jurisdiction == 7)] <- "injunction"
d$jurisdiction[which(d$jurisdiction == 8)] <- "mandamus"
d$jurisdiction[which(d$jurisdiction == 9)] <- "original"
d$jurisdiction[which(d$jurisdiction == 10)] <- "prohibition"
d$jurisdiction[which(d$jurisdiction == 12)] <- "stay"
d$jurisdiction[which(d$jurisdiction == 13)] <- "writ of error"
d$jurisdiction[which(d$jurisdiction == 14)] <- "writ of habeus corpus"
d$jurisdiction[which(d$jurisdiction == 15)] <- "unspecified"
```
## Reading in petition data
```{r}
read_petition_total <- function(x, y) {
  z <- read_excel(x, skip = 1) %>% 
    drop_na() %>% 
    clean_names() %>% 
    rename("granted" = "terminated",
           "denied" = "x5",
           "dismissed" = "x6") %>% 
    mutate(year = y)
  z[2:5, c(1, 3:6, 8)]
}
read_p_total <- function(x, y) {
  z <- read_excel(x, skip = 9) %>% 
    drop_na() %>% 
    clean_names() %>% 
    rename("circuit_and_nature_of_proceeding" = "of_proceeding") %>% 
    mutate(year = y)
  z[2:5, c(1, 3:6, 8)]
}

read_annoyed <- function(x, y) {
  z <- read_excel(x, skip = 11) %>% 
    drop_na() %>% 
    clean_names() %>% 
    rename("circuit_and_nature_of_proceeding" = "of_proceeding") %>% 
    mutate(year = y)
  z[2:5, c(1, 3:6, 8)]
}

p_2019 <- read_petition_total("raw_data/jb_b2_0930.2019.xlsx", 2019)
p_2018 <- read_petition_total("raw_data/jb_b2_0930.2018.xlsx", 2018)
p_2017 <- read_petition_total("raw_data/jb_b2_0930.2017.xlsx", 2017)
p_2016 <- read_petition_total("raw_data/jb_b2_0930.2016.xlsx", 2016)
p_2015 <- read_p_total("raw_data/B02Sep15.xlsx", 2015)
p_2014 <- read_p_total("raw_data/B02Sep14.xlsx", 2014)
p_2013 <- read_p_total("raw_data/B02Sep13.xlsx", 2013)
p_2012 <- read_p_total("raw_data/B02Sep12.xlsx", 2012)
p_2011 <- read_p_total("raw_data/B02Sep11.xlsx", 2011)
p_2010 <- read_annoyed("raw_data/B02Sep10.xlsx", 2010)
p_2009 <- read_p_total("raw_data/B02Sep09.xlsx", 2009)
p_2008 <- read_p_total("raw_data/B02Sep08.xlsx", 2008)
p_2007 <- read_p_total("raw_data/B02Sep07.xlsx", 2007)
p_2006 <- read_annoyed("raw_data/b2_2.xlsx", 2006)
p_2005 <- read_p_total("raw_data/b2_1.xlsx", 2005)

roberts_circuit <- rbind(p_2019, p_2018, p_2017, p_2016, p_2015, p_2014, p_2013, p_2012, p_2011, p_2010, p_2009, p_2008, p_2007, p_2006, p_2005)

# These are all of the years that Roberts has been Chief Justice. I could probably find more data but this took a lot
# of random work to even get, so I don't really want to
# go about prepping more data for analysis haha. 

roberts_model <- stan_glm(as.numeric(granted) ~ circuit_and_nature_of_proceeding,
         data = roberts_circuit,
         refresh = 0)

take_2 <- stan_glm(as.numeric(granted) ~ circuit_and_nature_of_proceeding + year - 1,
         data = roberts_circuit,
         refresh = 0)

print(roberts_model, digits = 3)
print(take_2, digits = 3)

```

